schema {
  query: Query
  mutation: Mutation
}

type Query {
  viewer: Viewer!
  productById(id: ID!): Product @lookup @internal
}

type Mutation {
  addProductToCart(input: AddProductToCartInput!): AddProductToCartPayload!
    @authorize
    @cost(weight: "10")
  removeProductFromCart(input: RemoveProductFromCartInput!): RemoveProductFromCartPayload!
    @authorize
    @cost(weight: "10")
  checkout: CheckoutPayload! @authorize @cost(weight: "10")
}

type AddProductToCartPayload {
  cart: Cart
  errors: [AddProductToCartError!]
}

type Cart {
  id: ID!
  items(
    "Returns the first _n_ elements from the list."
    first: Int
    "Returns the elements in the list that come after the specified cursor."
    after: String
    "Returns the last _n_ elements from the list."
    last: Int
    "Returns the elements in the list that come before the specified cursor."
    before: String
  ): CartItemsConnection
    @listSize(
      assumedSize: 50
      slicingArguments: ["first", "last"]
      slicingArgumentDefaultValue: 10
      sizedFields: ["edges", "nodes"]
      requireOneSlicingArgument: false
    )
    @cost(weight: "10")
  createdAt: DateTime!
}

type CartItem {
  id: ID!
  addedAt: DateTime!
  product: Product!
  quantity: Int!
}

"A connection to a list of items."
type CartItemsConnection @shareable {
  "Information to aid in pagination."
  pageInfo: PageInfo!
  "A list of edges."
  edges: [CartItemsEdge!]
  "A flattened list of the nodes."
  nodes: [CartItem!]
}

"An edge in a connection."
type CartItemsEdge @shareable {
  "A cursor for use in pagination."
  cursor: String!
  "The item at the end of the edge."
  node: CartItem!
}

type CheckoutPayload {
  cart: Cart
}

"Information about pagination in a connection."
type PageInfo @shareable {
  "Indicates whether more edges exist following the set defined by the clients arguments."
  hasNextPage: Boolean!
  "Indicates whether more edges exist prior the set defined by the clients arguments."
  hasPreviousPage: Boolean!
  "When paginating backwards, the cursor to continue."
  startCursor: String
  "When paginating forwards, the cursor to continue."
  endCursor: String
}

type Product @key(fields: "id") {
  id: ID!
}

type ProductAmountCannotBeLowerThanOneError implements Error {
  message: String!
}

type RemoveProductFromCartPayload {
  cart: Cart
  errors: [RemoveProductFromCartError!]
}

type Viewer {
  cart: Cart! @authorize @cost(weight: "10")
}

interface Error {
  message: String!
}

union AddProductToCartError = ProductAmountCannotBeLowerThanOneError

union RemoveProductFromCartError = ProductAmountCannotBeLowerThanOneError

input AddProductToCartInput {
  productId: ID!
  quantity: Int!
}

input RemoveProductFromCartInput {
  productId: ID!
  quantity: Int!
}

"Defines when a policy shall be executed."
enum ApplyPolicy {
  "Before the resolver was executed."
  BEFORE_RESOLVER
  "After the resolver was executed."
  AFTER_RESOLVER
  "The policy is applied in the validation step before the execution."
  VALIDATION
}

enum ScalarSerializationType {
  STRING
  BOOLEAN
  INT
  FLOAT
  OBJECT
  LIST
}

"The `DateTime` scalar type represents a date and time with time zone offset information."
scalar DateTime
  @serializeAs(
    type: STRING
    pattern: "^\\d{4}-\\d{2}-\\d{2}[Tt]\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{1,9})?(?:[Zz]|[+-]\\d{2}:\\d{2})$"
  )
  @specifiedBy(url: "https://scalars.graphql.org/chillicream/date-time.html")

scalar FieldSelectionSet

"The authorize directive."
directive @authorize(
  "The name of the authorization policy that determines access to the annotated resource."
  policy: String
  "Roles that are allowed to access the annotated resource."
  roles: [String!]
  "Defines when the authorize directive shall be applied. By default the authorize directive is applied before the resolver is executed."
  apply: ApplyPolicy! = BEFORE_RESOLVER
) repeatable on OBJECT | FIELD_DEFINITION

"The purpose of the `cost` directive is to define a `weight` for GraphQL types, fields, and arguments. Static analysis can use these weights when calculating the overall cost of a query or response."
directive @cost(
  "The `weight` argument defines what value to add to the overall cost for every appearance, or possible appearance, of a type, field, argument, etc."
  weight: String!
) on
  | SCALAR
  | OBJECT
  | FIELD_DEFINITION
  | ARGUMENT_DEFINITION
  | ENUM
  | INPUT_FIELD_DEFINITION

directive @internal on OBJECT | FIELD_DEFINITION

"""
The @key directive is used to designate an entity's unique key,
which identifies how to uniquely reference an instance of
an entity across different source schemas.
"""
directive @key("The field selection set syntax." fields: FieldSelectionSet!) repeatable on
  | OBJECT
  | INTERFACE

"The purpose of the `@listSize` directive is to either inform the static analysis about the size of returned lists (if that information is statically available), or to point the analysis to where to find that information."
directive @listSize(
  "The `assumedSize` argument can be used to statically define the maximum length of a list returned by a field."
  assumedSize: Int
  "The `slicingArguments` argument can be used to define which of the field's arguments with numeric type are slicing arguments, so that their value determines the size of the list returned by that field. It may specify a list of multiple slicing arguments."
  slicingArguments: [String!]
  "The `slicingArgumentDefaultValue` argument can be used to define a default value for a slicing argument, which is used if the argument is not present in a query."
  slicingArgumentDefaultValue: Int
  "The `sizedFields` argument can be used to define that the value of the `assumedSize` argument or of a slicing argument does not affect the size of a list returned by a field itself, but that of a list returned by one of its sub-fields."
  sizedFields: [String!]
  "The `requireOneSlicingArgument` argument can be used to inform the static analysis that it should expect that exactly one of the defined slicing arguments is present in a query. If that is not the case (i.e., if none or multiple slicing arguments are present), the static analysis may throw an error."
  requireOneSlicingArgument: Boolean = true
) on FIELD_DEFINITION

"""
The @lookup directive is used within a source schema to specify output fields
that can be used by the distributed GraphQL executor to resolve an entity by
a stable key.
"""
directive @lookup on FIELD_DEFINITION

directive @serializeAs(
  "The primitive type a scalar is serialized to."
  type: [ScalarSerializationType!]!
  "The ECMA-262 regex pattern that the serialized scalar value conforms to."
  pattern: String
) on SCALAR

directive @shareable repeatable on OBJECT | FIELD_DEFINITION
