trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: CmdLine@2
    displayName: 'Export Accounts Subgraph Schema'
    inputs:
      script: |
        dotnet tool restore
        dotnet run --project ./Subgraphs/Accounts -- schema export --output schema.graphql
        dotnet fusion subgraph pack -w ./Subgraphs/Accounts
  - task: CmdLine@2
    displayName: 'Begin Accounts Subgraph Deployment'
    inputs:
      script: |
        echo dotnet barista fusion-configuration publish begin --tag reviews-1.0.0 --api-id QXBpCmcyOGVhZWE0NWFlODg0ODExODIzMmQ3YTM5NTRkZTljZA== --subgraph-name accounts --stage dev --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration publish begin --tag reviews-1.0.0 --api-id QXBpCmcyOGVhZWE0NWFlODg0ODExODIzMmQ3YTM5NTRkZTljZA== --subgraph-name accounts --stage dev --api-key $(BaristaApiKey)
        echo dotnet barista fusion-configuration publish start
        dotnet barista fusion-configuration publish start
        echo dotnet barista fusion-configuration download --api-id QXBpCmcyOGVhZWE0NWFlODg0ODExODIzMmQ3YTM5NTRkZTljZA== --stage dev --output-file gateway.fgp --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration download --api-id QXBpCmcyOGVhZWE0NWFlODg0ODExODIzMmQ3YTM5NTRkZTljZA== --stage dev --output-file gateway.fgp --api-key $(BaristaApiKey)
        echo dotnet fusion compose -p ./gateway -s ./Subgraphs/Accounts --enable-nodes
        dotnet fusion compose -p ./gateway -s ./Subgraphs/Accounts --enable-nodes
  - task: Docker@2
    displayName: 'Build Accounts Subgraph Container'
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'accounts-subgraph'
      command: 'buildAndPush'
      Dockerfile: './Subgraphs/Accounts/dockerfile'
  - task: AzureContainerApps@1
    displayName: 'Deploy Accounts Subgraph Container'
    inputs:
      azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
      imageToDeploy: 'cccfusionusshop.azurecr.io/shop-gateway:$(Build.BuildId)'
      containerAppName: 'accounts-subgraph'
      resourceGroup: 'ccc-fusion-us'
  - task: CmdLine@2
    displayName: 'Complete Accounts Subgraph Deployment'
    inputs:
      script: |
        dotnet barista fusion-configuration publish commit --configuration ./gateway.fgp