trigger:
  branches:
   include:
     - main
  paths:
    include:
      - /Subgraphs/Reviews
      - /.devops/deploy-reviews.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: CmdLine@2
    displayName: 'Export Reviews Subgraph Schema'
    inputs:
      script: |
        dotnet tool restore
        dotnet run --project ./Subgraphs/Reviews -- schema export --output schema.graphql
        dotnet fusion subgraph config set http --url $(SubgraphUrl) -w ./Subgraphs/Reviews
        dotnet fusion subgraph pack -w ./Subgraphs/Reviews
      failOnStderr: true
  - task: CmdLine@2
    displayName: 'Begin Reviews Subgraph Deployment'
    inputs:
      script: |
        dotnet barista fusion-configuration publish begin --tag reviews-$(Build.BuildId) --api-id $(BaristaApiId) --subgraph-name reviews --stage dev --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration publish start --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration download --api-id $(BaristaApiId) --stage dev --output-file gateway.fgp --api-key $(BaristaApiKey)
        dotnet fusion compose -p ./gateway -s ./Subgraphs/Reviews --enable-nodes
      failOnStderr: true
  - task: Docker@2
    displayName: 'Build Reviews Subgraph Container'
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'reviews-subgraph'
      command: 'buildAndPush'
      Dockerfile: './Subgraphs/Reviews/dockerfile'
  - task: AzureContainerApps@1
    displayName: 'Deploy Reviews Subgraph Container'
    inputs:
      azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
      imageToDeploy: 'cccfusionusshop.azurecr.io/reviews-subgraph:$(Build.BuildId)'
      containerAppName: 'reviews-subgraph'
      resourceGroup: 'ccc-fusion-us'
  - task: CmdLine@2
    displayName: 'Complete Reviews Subgraph Deployment'
    inputs:
      script: 'dotnet barista fusion-configuration publish commit --configuration ./gateway.fgp --api-key $(BaristaApiKey)'
      failOnStderr: true