trigger:
  branches:
   include:
     - main
  paths:
    include:
      - Subgraphs/Shipping
      - .devops/deploy-shipping.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: CmdLine@2
    displayName: 'Export Shipping Subgraph Schema'
    inputs:
      script: |
        dotnet tool restore
        dotnet run --project ./Subgraphs/Shipping -- schema export --output schema.graphql
        dotnet fusion subgraph config set http --url $(SubgraphUrl) -w ./Subgraphs/Shipping
        dotnet fusion subgraph pack -w ./Subgraphs/Shipping
      failOnStderr: true
  - task: Docker@2
    displayName: 'Build Shipping Subgraph Container'
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'shipping-subgraph'
      command: 'buildAndPush'
      Dockerfile: './Subgraphs/Shipping/dockerfile'
  - task: CmdLine@2
    displayName: 'Begin Shipping Subgraph Deployment'
    inputs:
      script: |
        dotnet barista fusion-configuration publish begin --tag shipping-$(Build.BuildId) --api-id $(BaristaApiId) --subgraph-name shipping --stage dev --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration publish start --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration download --api-id $(BaristaApiId) --stage dev --output-file gateway.fgp --api-key $(BaristaApiKey)
        dotnet fusion compose -p ./gateway -s ./Subgraphs/Shipping --enable-nodes
      failOnStderr: true
  - task: AzureContainerApps@1
    displayName: 'Deploy Shipping Subgraph Container'
    inputs:
      azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
      imageToDeploy: 'cccfusionusshop.azurecr.io/shipping-subgraph:$(Build.BuildId)'
      containerAppName: 'shipping-subgraph'
      resourceGroup: 'ccc-fusion-us'
  - task: CmdLine@2
    displayName: 'Complete Shipping Subgraph Deployment'
    inputs:
      script: 'dotnet barista fusion-configuration publish commit --configuration ./gateway.fgp --api-key $(BaristaApiKey)'
      failOnStderr: true