trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: Docker@2
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'shop-gateway'
      command: 'buildAndPush'
      Dockerfile: './Gateway/dockerfile'
  - task: AzureContainerApps@1
    inputs:
      azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
      imageToDeploy: 'cccfusionusshop.azurecr.io/shop-gateway:$(Build.BuildId)'
      containerAppName: 'shop-gateway'
      resourceGroup: 'ccc-fusion-us'