trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: CmdLine@2
    displayName: 'Build Gateway Container'
    inputs:
      script: |
        dotnet publish ./Gateway --os linux --arch x64 /t:PublishContainer -c Release /p:ContainerImageTags=$(Version) /p:ContainerImageName=$(ContainerRegistry)/shop-gateway'
        docker image tag chillicream/shop-gateway:$(Version) $(ContainerRegistry)/shop-gateway:$(Version)
  - task: Docker@2
    displayName: 'Publiush Gateway Container'
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'shop-gateway'
      command: 'push'
      tags: '$(Version)'
