trigger:
  branches:
   include:
     - main
  paths:
    include:
      - Subgraphs/Accounts
      - .devops/deploy-accounts.yml

pool:
  vmImage: ubuntu-latest

steps:
  - task: UseDotNet@2
    displayName: 'Install .NET SDK'
    inputs:
      packageType: 'sdk'
      useGlobalJson: true
  - task: CmdLine@2
    displayName: 'Export Accounts Subgraph Schema'
    inputs:
      script: |
        dotnet tool restore
        dotnet run --project ./Subgraphs/Accounts -- schema export --output schema.graphql
        dotnet fusion subgraph config set http --url $(SubgraphUrl) -w ./Subgraphs/Accounts
        dotnet fusion subgraph pack -w ./Subgraphs/Accounts
      failOnStderr: true
  - task: Docker@2
    displayName: 'Build Accounts Subgraph Container'
    inputs:
      containerRegistry: 'Fusion Demo Registry'
      repository: 'accounts-subgraph'
      command: 'buildAndPush'
      Dockerfile: './Subgraphs/Accounts/dockerfile'
  - task: CmdLine@2
    displayName: 'Begin Accounts Subgraph Deployment'
    inputs:
      script: |
        dotnet barista fusion-configuration publish begin --tag accounts-$(Build.BuildId) --api-id $(BaristaApiId) --subgraph-name accounts --stage dev --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration publish start --api-key $(BaristaApiKey)
        dotnet barista fusion-configuration download --api-id $(BaristaApiId) --stage dev --output-file ./gateway.fgp --api-key $(BaristaApiKey)
        dotnet fusion compose -p ./gateway.fgp -s ./Subgraphs/Accounts --enable-nodes
      failOnStderr: true
  - task: AzureContainerApps@1
    displayName: 'Deploy Accounts Subgraph Container'
    inputs:
      azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
      imageToDeploy: 'cccfusionusshop.azurecr.io/accounts-subgraph:$(Build.BuildId)'
      containerAppName: 'accounts-subgraph'
      resourceGroup: 'ccc-fusion-us'
  - task: CmdLine@2
    displayName: 'Complete Accounts Subgraph Deployment'
    inputs:
      script: 'dotnet barista fusion-configuration publish commit --configuration ./gateway.fgp --api-key $(BaristaApiKey)'
      failOnStderr: true