trigger:
  branches:
   include:
     - main
  paths:
    include:
      - Subgraphs/Reviews
      - .devops/deploy-reviews.yml
      - .config

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: SubgraphConfiguration
        displayName: 'Subgraph Configuration'
        steps:
          - checkout: self
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              useGlobalJson: true
          - task: CmdLine@2
            displayName: 'Create Subgraph Configuration'
            inputs:
              script: |
                dotnet tool restore
                dotnet run --project ./Subgraphs/Reviews -- schema export --output schema.graphql
                dotnet fusion subgraph pack -w ./Subgraphs/Reviews
              failOnStderr: true
          - task: PublishPipelineArtifact@1
            displayName: 'Upload Subgraph Configuration'
            inputs:
              targetPath: './Subgraphs/Reviews/reviews.fsp'
              artifact: 'SubgraphConfig'
              publishLocation: 'pipeline'
      - job: SubgraphContainer
        displayName: 'Subgraph Container'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build Subgraph Container'
            inputs:
              containerRegistry: 'Fusion Demo Registry'
              repository: 'reviews-subgraph'
              command: 'buildAndPush'
              Dockerfile: './Subgraphs/Reviews/dockerfile'

  - stage: Development
    jobs: 
      - deployment: DeploySubgraph
        displayName: 'Deploy Subgraph'
        environment: Development
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: 'Install .NET SDK'
                inputs:
                  packageType: 'sdk'
                  useGlobalJson: true
              - task: DownloadBuildArtifacts@1
                displayName: 'Download Subgraph Configuration'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'SubgraphConfig'
                  downloadPath: '$(System.ArtifactsDirectory)/subgraph'
              - task: CmdLine@2
                displayName: 'Begin Subgraph Deployment'
                inputs:
                  script: |
                    dotnet tool restore
                    dotnet fusion subgraph config set http --url $(DevEuSubgraphUrl) -c $(System.ArtifactsDirectory)/subgraph/reviews.fsp
                    dotnet barista fusion-configuration publish begin --tag reviews-$(Build.BuildId) --api-id $(BaristaApiId) --subgraph-name reviews --stage dev --api-key $(BaristaApiKey)
                    dotnet barista fusion-configuration publish start --api-key $(BaristaApiKey)
                    dotnet barista fusion-configuration download --api-id $(BaristaApiId) --stage dev --output-file ./Gateway/gateway.fgp --api-key $(BaristaApiKey)
                    dotnet fusion compose -p ./Gateway/gateway.fgp -s $(System.ArtifactsDirectory)/subgraph
                  failOnStderr: true
              - task: AzureContainerApps@1
                displayName: 'Deploy Subgraph Container'
                inputs:
                  azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
                  imageToDeploy: 'cccfusionusshop.azurecr.io/reviews-subgraph:$(Build.BuildId)'
                  containerAppName: 'reviews-subgraph-dev-eu'
                  resourceGroup: 'ccc-fusion-eu'
              - task: CmdLine@2
                displayName: 'Complete Subgraph Deployment'
                inputs:
                  script: 'dotnet barista fusion-configuration publish commit --configuration ./Gateway/gateway.fgp --api-key $(BaristaApiKey)'
                  failOnStderr: true
  - stage: Production
    jobs: 
      - deployment: DeploySubgraph
        displayName: 'Deploy Subgraph'
        environment: Production
        strategy:
          runOnce:
            deploy:
              steps:
              - checkout: self
              - task: UseDotNet@2
                displayName: 'Install .NET SDK'
                inputs:
                  packageType: 'sdk'
                  useGlobalJson: true
              - task: DownloadBuildArtifacts@1
                displayName: 'Download Subgraph Configuration'
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'SubgraphConfig'
                  downloadPath: '$(System.ArtifactsDirectory)/subgraph'
              - task: CmdLine@2
                displayName: 'Begin Subgraph Deployment'
                inputs:
                  script: |
                    dotnet tool restore
                    dotnet fusion subgraph config set http --url $(EuSubgraphUrl) -c $(System.ArtifactsDirectory)/subgraph/reviews.fsp
                    dotnet barista fusion-configuration publish begin --tag reviews-$(Build.BuildId) --api-id $(BaristaApiId) --subgraph-name reviews --stage prod --api-key $(BaristaApiKey)
                    dotnet barista fusion-configuration publish start --api-key $(BaristaApiKey)
                    dotnet barista fusion-configuration download --api-id $(BaristaApiId) --stage prod --output-file ./Gateway/gateway.fgp --api-key $(BaristaApiKey)
                    dotnet fusion compose -p ./Gateway/gateway.fgp -s $(System.ArtifactsDirectory)/subgraph
                  failOnStderr: true
              - task: AzureContainerApps@1
                displayName: 'Deploy Subgraph Container'
                inputs:
                  azureSubscription: 'MVP Credits(621759a8-3784-47fa-b2a9-b69c462fce44)'
                  imageToDeploy: 'cccfusionusshop.azurecr.io/reviews-subgraph:$(Build.BuildId)'
                  containerAppName: 'reviews-subgraph-eu'
                  resourceGroup: 'ccc-fusion-eu'
              - task: CmdLine@2
                displayName: 'Complete Subgraph Deployment'
                inputs:
                  script: 'dotnet barista fusion-configuration publish commit --configuration ./Gateway/gateway.fgp --api-key $(BaristaApiKey)'
                  failOnStderr: true